1\. Задан двухмерный массив ar1 размерности (10, 10), состоящий из случайных целых чисел в пределах от 0 до 15. Вычислить разность s_odd - s_even, где s_odd - сумма элементов, стоящих на позиции (x, y), где (x + y) является нечетным числом; s_even - сумма элементов, стоящих на позиции (x, y), где (x + y) является четным числом.
Решить задачу средствами numpy и/или pandas. Не использовать циклы и конструкции стандартного Python там, где можно использовать возможности данных библиотек


In [690]:
import numpy as np
import pandas as pd

In [691]:
rng = np.random.default_rng()
ar1 = rng.integers(0, 15, size=(10, 10))  # 15 + 1
ar1

array([[ 8,  7, 11,  1, 10,  9,  4,  3,  8,  4],
       [ 8,  3, 10,  4, 12,  3,  0,  2,  8, 11],
       [ 7, 10,  0,  0,  1, 12, 10,  5,  4, 11],
       [11,  3,  4,  4, 10, 11,  3,  1,  3,  5],
       [ 4,  3,  7, 13,  5, 14,  0,  6,  9, 13],
       [ 8, 11,  1, 11,  4,  1,  9,  2,  7, 10],
       [12, 10, 13, 11, 14,  5,  1,  8, 10,  7],
       [13, 10, 10, 14,  6,  3, 12, 10,  8,  0],
       [ 3,  3,  3,  5, 11,  0, 12,  7,  8,  1],
       [14,  6, 12, 14,  3,  1, 10, 13,  2,  9]], dtype=int64)

In [692]:
idx_x = np.arange(ar1.shape[0])
idx_y = np.arange(ar1.shape[1]).reshape(-1, 1)
idx_s_odd = (idx_x + idx_y) % 2 == 1
idx_s_even = ~idx_s_odd
idx_s_odd

array([[False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]])

In [693]:
s_odd = ar1[idx_s_odd].sum()
s_even = ar1[idx_s_even].sum()
s_odd - s_even

19

2\. Датасет: Chinook_Sqlite.sqlite
С помощью кода на Python с использованием sqlite3 и SQL решить задачу. Реализовать функции на Python:
1. Которая возвращает все имеющиеся жанры.
2. Которая возвращает ID жанров, в которых написано более 100 треков, и их (жанров) название.


In [694]:
import sqlite3

In [695]:
def find_all_genres(cur: sqlite3.Cursor) -> list:
    stmt = 'SELECT * FROM Genre'
    return cur.execute(stmt).fetchall()


def find_genres_ids_by_n_tracks_gt(cur: sqlite3.Cursor, n: int = 100) -> list:
    stmt = '''
    SELECT G.GenreId, G.Name FROM Genre G
    JOIN Track T ON G.GenreId = T.GenreId
    GROUP BY T.GenreId HAVING COUNT(T.GenreId) > ?'''
    return cur.execute(stmt, [n]).fetchall()

In [696]:
con = sqlite3.connect('data/Chinook_Sqlite.sqlite')
cur = con.cursor()

In [697]:
find_all_genres(cur)

[(1, 'Rock'),
 (2, 'Jazz'),
 (3, 'Metal'),
 (4, 'Alternative & Punk'),
 (5, 'Rock And Roll'),
 (6, 'Blues'),
 (7, 'Latin'),
 (8, 'Reggae'),
 (9, 'Pop'),
 (10, 'Soundtrack'),
 (11, 'Bossa Nova'),
 (12, 'Easy Listening'),
 (13, 'Heavy Metal'),
 (14, 'R&B/Soul'),
 (15, 'Electronica/Dance'),
 (16, 'World'),
 (17, 'Hip Hop/Rap'),
 (18, 'Science Fiction'),
 (19, 'TV Shows'),
 (20, 'Sci Fi & Fantasy'),
 (21, 'Drama'),
 (22, 'Comedy'),
 (23, 'Alternative'),
 (24, 'Classical'),
 (25, 'Opera')]

In [698]:
find_genres_ids_by_n_tracks_gt(cur, 100)

[(1, 'Rock'),
 (2, 'Jazz'),
 (3, 'Metal'),
 (4, 'Alternative & Punk'),
 (7, 'Latin')]

3\. Датасет: album_artist.xlsx
С помощью кода на Python с использованием xlwings решить задачу. Вынести названия артистов на отдельный лист "Артисты" и присвоить каждому артисту уникальный идентификатор. Заменить названия артистов на исходном листе на идентификаторы с листа "Артисты".


In [699]:
import xlwings as xw

In [700]:
wb = xw.Book('data/album_artist.xlsx')

In [701]:
data_sheet: xw.Sheet = wb.sheets['Sheet1']
artists_sheet: xw.Sheet = wb.sheets.add('Артисты')

In [702]:
artist_names_range: xw.Range = data_sheet.range('D2').expand('down')
artist_names = sorted(set(artist_names_range.value))

In [703]:
artists_map = {name: id_ for id_, name in enumerate(artist_names)}
artists_sheet.range('A1').value = ('name', 'id')
artists_sheet.range('A2').value = list(artists_map.items())

In [704]:
artist_names_range.value = list(map(lambda x: [artists_map[x]], artist_names_range.value))

In [705]:
# wb.save()
wb.close()

4\. Датасет: us-countries.csv
Создайте таблицу, где по строкам располагаются названия штатов, по столбцам - каждый из 12 месяцев 2020 года, а в ячейках таблицы хранится суммарное количество смертей в данном штате в этот месяц. Если информация за какой-то месяц отсутствует, укажите в этой ячейке значение 0.


In [706]:
us_countries_df = pd.read_csv('data/us-counties.csv', sep=',', parse_dates=['date'])
us_countries_df = us_countries_df[us_countries_df['date'].dt.year == 2020]
us_countries_df.head()

date     county       state     fips  cases  deaths
0 2020-01-21  Snohomish  Washington  53061.0      1     0.0
1 2020-01-22  Snohomish  Washington  53061.0      1     0.0
2 2020-01-23  Snohomish  Washington  53061.0      1     0.0
3 2020-01-24       Cook    Illinois  17031.0      1     0.0
4 2020-01-24  Snohomish  Washington  53061.0      1     0.0

In [707]:
# Способ 1. Сводная таблица
pivot_table = us_countries_df.pivot_table(
    'deaths',
    index=us_countries_df['state'].rename(None),
    columns=us_countries_df['date'].dt.month.rename(None),
    aggfunc='sum'
)
pivot_table = pivot_table.fillna(0).astype(int)
pivot_table.head()

1   2     3      4      5       6       7       8       9   \
Alabama      0   0    42   4044  14438   23697   38436   58883   71419   
Alaska       0   0     8    173    243     291     496     843    1265   
Arizona      0   0   118   4870  19864   37510   79906  138063  161423   
Arkansas     0   0    36   1007   3137    5895   10829   19077   32549   
California   0   0  1113  30176  99379  155690  232621  349458  438311   

                10      11      12  
Alabama      85064   98538  131827  
Alaska        1890    2802    5136  
Arizona     179976  189527  237564  
Arkansas     51328   66765   95245  
California  522654  551791  683920

In [708]:
# Способ 2. Groupby
groupby_table = us_countries_df.groupby([
    us_countries_df['state'].rename(None),
    us_countries_df['date'].dt.month.rename(None)
])['deaths'].sum()
grouped_table = groupby_table.unstack()
grouped_table = grouped_table.fillna(0).astype(int)
grouped_table.head()

1   2     3      4      5       6       7       8       9   \
Alabama      0   0    42   4044  14438   23697   38436   58883   71419   
Alaska       0   0     8    173    243     291     496     843    1265   
Arizona      0   0   118   4870  19864   37510   79906  138063  161423   
Arkansas     0   0    36   1007   3137    5895   10829   19077   32549   
California   0   0  1113  30176  99379  155690  232621  349458  438311   

                10      11      12  
Alabama      85064   98538  131827  
Alaska        1890    2802    5136  
Arizona     179976  189527  237564  
Arkansas     51328   66765   95245  
California  522654  551791  683920

5\. По данным из файла data/meals.json сформировать словарь, в котором по идентификатору блюда можно получить список ингредиентов.

In [709]:
import json

In [710]:
def read_json(path: str) -> dict:
    with open(path) as f:
        return json.load(f)

In [711]:
meals = read_json('data/meals.json')
meals = meals['meals']
meals_ingredients = {}
for meal in meals:
    meals_ingredients[meal['idMeal']] = [
        v for k, v in meal.items() if k.startswith('strIngredient') and v
    ]
meals_ingredients

{'52768': ['digestive biscuits',
  'butter',
  'Bramley apples',
  'butter, softened',
  'caster sugar',
  'free-range eggs, beaten',
  'ground almonds',
  'almond extract',
  'flaked almonds'],
 '52893': ['Plain Flour',
  'Caster Sugar',
  'Butter',
  'Braeburn Apples',
  'Butter',
  'Demerara Sugar',
  'Blackberrys',
  'Cinnamon',
  'Ice Cream'],
 '53049': ['Milk',
  'Oil',
  'Eggs',
  'Flour',
  'Baking Powder',
  'Salt',
  'Unsalted Butter',
  'Sugar',
  'Peanut Butter'],
 '53050': ['Chicken Thighs',
  'Challots',
  'Ginger',
  'Garlic Clove',
  'Cayenne Pepper',
  'Turmeric',
  'Cumin',
  'Coriander',
  'Fennel',
  'Tamarind Paste',
  'Coconut Milk',
  'Sugar',
  'Water']}

6\. Датасет: Womens Clothing E-Commerce Reviews.csv
Для каждого уникального значения в столбце Division Name найти топ-5 самых часто используемых слов в описании отзыва. Исключить из рассмотрения стоп-слова.


In [712]:
import nltk
from nltk.corpus import stopwords
from nltk.corpus.reader.wordnet import VERB, NOUN
import re

In [713]:
w_clothing_reviews_df = pd.read_csv('data/Womens Clothing E-Commerce Reviews.csv', sep=',', index_col=0)
w_clothing_reviews_df = w_clothing_reviews_df[['Review Text', 'Division Name']].dropna()
w_clothing_reviews_df.head()

Review Text   Division Name
0  Absolutely wonderful - silky and sexy and comf...       Initmates
1  Love this dress!  it's sooo pretty.  i happene...         General
2  I had such high hopes for this dress and reall...         General
3  I love, love, love this jumpsuit. it's fun, fl...  General Petite
4  This shirt is very flattering to all due to th...         General

In [714]:
pattern = re.compile(r'[^a-z0-9\s]', re.IGNORECASE)


def agg(s: pd.Series, lemmatizer: nltk.WordNetLemmatizer, stop_words: set[str]):
    text = pattern.sub(' ', ' '.join(s.array).casefold())
    normalized_text = []
    for word in nltk.word_tokenize(text):
        pos = VERB if word == 'was' else NOUN
        lemma = lemmatizer.lemmatize(word, pos)
        if lemma not in stop_words:
            normalized_text.append(lemma)
    return nltk.FreqDist(normalized_text).most_common(5)

In [715]:
lemmatizer = nltk.WordNetLemmatizer()
stop_words = set(stopwords.words('english'))
w_clothing_reviews_df.groupby('Division Name')['Review Text'].agg(lambda s: agg(s, lemmatizer, stop_words))

Division Name
General           [(dress, 6542), (fit, 6048), (size, 5601), (lo...
General Petite    [(dress, 4657), (fit, 3549), (size, 3298), (lo...
Initmates         [(fit, 580), (size, 538), (love, 526), (like, ...
Name: Review Text, dtype: object

7\. Датасет: people.*.csv
В people.*.csv найти номера карт, сумма цифр в которых кратна 7. Выполнить задание с использованием Dask, распараллелив процесс обработки данных. Выполнить задание с использованием Dask (корректным!), распараллелив процесс обработки данных (использование Dask должно приводить к истинной параллельной обработке данных).


In [716]:
import dask.dataframe as dd

In [717]:
cards_s: dd.Series = dd.read_csv('data/people/*.csv')['card']
cards_s.head()

0    5438 1968 9922 9337
1      3769 395661 41045
2    2657 4280 9607 4252
3      3454 218578 39569
4    4994 8117 4888 3147
Name: card, dtype: object

In [718]:
mask = cards_s.apply(lambda x: sum([int(i) for i in x if i.isdigit()]), meta=('card', int)) % 7 == 0
cards_s[mask].compute()

8      2718 8407 9504 4344
22       3435 949578 19046
31       3769 780398 39694
32     4904 9489 9196 8990
33       3770 280012 98351
              ...         
990      3706 093760 91856
992    4895 9639 6182 3803
996      3473 326557 62424
998    4796 5663 9678 4738
999    5515 8388 1476 5236
Name: card, Length: 449, dtype: object

8\. Подсчитать, сколько раз во всех текстовых файлах, лежащих в каталоге fish, встречаются слова, начинающиеся с прописной буквы. Выполнить задание с использованием Dask, распараллелив процесс обработки данных. Выполнить задание с использованием Dask (корректным!), распараллелив процесс обработки данных (использование Dask должно приводить к истинной параллельной обработке данных).

In [719]:
import dask.bag as db

In [720]:
fish_bag = db.read_text('data/fish/*.txt')

In [721]:
def reducer(accum: int, curr: str) -> int:
    for word in nltk.word_tokenize(curr):
        if word[0].isupper():
            accum += 1
    return accum


def combine(left, right):
    return left + right


n_titles = fish_bag.fold(reducer, combine, initial=0).compute()
n_titles

649

9\. Сгенерируйте 10 строк длиной в 10000 символов, состоящих из маленьких английских букв. Посчитайте, сколько раз в этих 10 строках встречается шаблон "x?y?z", где знак вопроса обозначает один любой символ. Решение этой задачи распараллелить, используя multiprocessing Pool. Сравнить продолжительность последовательного и параллельного решения задачи.

In [722]:
import string
import re  # noqa
from multiprocessing import Pool

In [723]:
rng = np.random.default_rng()
strings = [''.join(rng.choice(list(string.ascii_lowercase), size=10_000)) for _ in range(10)]
len(strings)

10

In [724]:
%%file 'src/nmatch.py'
import re


def nmatch(s: str, pattern: re.Pattern) -> int:
    return len(pattern.findall(s))

Overwriting src/nmatch.py


In [725]:
def blocking_mode(strings: list[str]) -> int:
    pattern = re.compile(r'x.y.z')
    n = 0
    for s in strings:
        n += nmatch(s, pattern)
    return n

In [726]:
def nonblocking_mode(strings: list[str]) -> int:
    from src.nmatch import nmatch
    pattern = re.compile(r'x.y.z')
    with Pool(8) as pool:
        result = pool.starmap(nmatch, zip(strings, [pattern] * len(strings)))
        return sum(result)

In [727]:
%%timeit

blocking_mode(strings)

121 µs ± 4.22 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [728]:
%%timeit

nonblocking_mode(strings)

211 ms ± 16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [729]:
assert blocking_mode(strings) == nonblocking_mode(strings)

10\. Создайте dask.array размерности 10 тыс на 5, заполненный случайными целыми числами на отрезке [0, 10]. Создайте версию этого массива, оставив только строки, в которых есть число 7

In [730]:
import dask.array as da

In [731]:
arr = da.random.randint(0, 10 + 1, size=(10_000, 5), chunks=(1000, 5))
arr.npartitions

10

In [732]:
arr[(arr[:] == 7).any(axis=1)].compute()

array([[ 2,  8,  2,  7,  7],
       [ 2,  9,  7, 10,  9],
       [ 7, 10,  2,  2,  7],
       ...,
       [ 8,  2,  7,  0,  9],
       [ 3,  7,  6,  3,  7],
       [ 7,  8,  3,  7,  7]])