In [1]:
import numpy as np
import statsmodels.api as sm
from sklearn import linear_model
import pandas as pd

In [2]:
df = pd.read_excel('data.xlsx', header=3)

df

№  Объем денежных накоплений в РФ миллиард руб. (y)  \
0    1                                           12345.0   
1    2                                           12091.9   
2    3                                           12339.7   
3    4                                           12450.6   
4    5                                           12832.1   
5    6                                           12892.1   
6    7                                           13224.5   
7    8                                           13449.9   
8    9                                           13476.8   
9   10                                           13588.9   
10  11                                           13600.4   
11  12                                           13768.5   
12  13                                           14796.6   
13  14                                           14424.2   
14  15                                           14607.3   
15  16                                           14688.0   
16  17                                           15057.3   
17  18                                           15161.0   
18  19                                           15534.6   
19  20                                           15544.5   
20  21                                           15644.4   
21  22                                           15717.8   

    Сводные данные о продаже наличной иностранной валюты кредитными организациями физическим лицам (x1)  \
0                                                2769                                                     
1                                                3065                                                     
2                                                3899                                                     
3                                                3790                                                     
4                                                3963                                                     
5                                                4224                                                     
6                                                4645                                                     
7                                                4914                                                     
8                                                4830                                                     
9                                                4815                                                     
10                                               4401                                                     
11                                               5189                                                     
12                                               3434                                                     
13                                               5195                                                     
14                                               5401                                                     
15                                               4239                                                     
16                                               4558                                                     
17                                               4675                                                     
18                                               6558                                                     
19                                               6253                                                     
20                                               5410                                                     
21                                               5023                                                     

    Курс рубля к доллару США (x2)  Цена нефти марки "Юралс" (x3)  \
0                           29.67                           94.2   
1                         

In [3]:
x: pd.DataFrame = df[[
    'Сводные данные о продаже наличной иностранной валюты кредитными организациями физическим лицам (x1)',
    'Курс рубля к доллару США (x2)',
    'Цена нефти марки "Юралс" (x3)',
    'Динамика потребительских цен по группам товаров и услуг (месяц к соответствующему месяцу предыдущего года,%)  (x4)',
]]
x = x.rename(columns={
    'Сводные данные о продаже наличной иностранной валюты кредитными организациями физическим лицам (x1)': 'x1',
    'Курс рубля к доллару США (x2)': 'x2',
    'Цена нефти марки "Юралс" (x3)': 'x3',
    'Динамика потребительских цен по группам товаров и услуг (месяц к соответствующему месяцу предыдущего года,%)  (x4)': 'x4',
})
x

x1     x2     x3   x4
0   2769  29.67   94.2  9.6
1   3065  28.94  101.1  9.5
2   3899  28.43  111.6  9.5
3   3790  27.50  119.7  9.6
4   3963  28.07  112.0  9.6
5   4224  28.08  112.0  9.4
6   4645  27.68  115.3  9.0
7   4914  28.86  109.6  8.2
8   4830  31.88  112.6  7.2
9   4815  29.90  108.7  7.2
10  4401  31.32  110.9  6.8
11  5189  32.20  108.0  6.1
12  3434  30.36  109.8  4.2
13  5195  28.95  119.2  3.7
14  5401  29.33  123.3  3.7
15  4239  29.36  117.8  3.6
16  4558  32.45  109.2  3.6
17  4675  32.82   93.5  4.3
18  6558  32.19  102.7  5.6
19  6253  32.92  113.5  5.9
20  5410  30.92  112.0  6.6
21  5023  31.53  110.8  6.5

In [4]:
y = df[['Объем денежных накоплений в РФ миллиард руб. (y)']]
y = y.rename(columns={
    'Объем денежных накоплений в РФ миллиард руб. (y)': 'y'
})
y

y
0   12345.0
1   12091.9
2   12339.7
3   12450.6
4   12832.1
5   12892.1
6   13224.5
7   13449.9
8   13476.8
9   13588.9
10  13600.4
11  13768.5
12  14796.6
13  14424.2
14  14607.3
15  14688.0
16  15057.3
17  15161.0
18  15534.6
19  15544.5
20  15644.4
21  15717.8

# STATSMODELS

In [5]:
x = sm.add_constant(x)

d:\it\coding\github projects\my-university\iii курс\(python) эконометрика\venv\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [26]:
model = sm.OLS(y, x).fit()

In [36]:
# Se
print(np.sqrt(model.mse_resid))

586.3207563508021


586.3207563508021

In [7]:
predictions = model.predict(x)
predictions

0     12343.514986
1     12374.592516
2     12643.690185
3     12389.738987
4     12597.514120
5     12780.357693
6     13021.107263
7     13562.979780
8     14172.863264
9     13932.807235
10    14013.890730
11    14722.002032
12    14146.659321
13    14892.235955
14    15014.895808
15    14519.866220
16    15132.487787
17    15145.389888
18    15555.455732
19    15350.269552
20    14498.055974
21    14425.724975
dtype: float64

In [8]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.806
Model:                            OLS   Adj. R-squared:                  0.761
Method:                 Least Squares   F-statistic:                     17.70
Date:                Sun, 26 Sep 2021   Prob (F-statistic):           6.83e-06
Time:                        20:31:41   Log-Likelihood:                -168.61
No. Observations:                  22   AIC:                             347.2
Df Residuals:                      17   BIC:                             352.7
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.04e+04   6169.698      1.686      0.110   -2616.991    2.34e+04
x1             0.4838      0.196      2.463      0.025       0.069       0.898
x2           130.3151    132.126      0.986      0.338    -148.446     409.076
x3            -6.4678     25.698     -0.252      0.804     -60.686      47.750
x4          -276.3727     78.946     -3.501      0.003    -442.935    -109.810
==============================================================================
Omnibus:                        5.043   Durbin-Watson:                   1.083
Prob(Omnibus):                  0.080   Jarque-Bera (JB):                2.978
Skew:                           0.808   Prob(JB):                        0.226
Kurtosis:                       3.797   Cond. No.                     2.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# SKLEARN

In [15]:
lm = linear_model.LinearRegression()
model = lm.fit(x, y)

AttributeError: 'LinearRegression' object has no attribute 'centered_tss'

In [10]:
predictions = lm.predict(x)
predictions

array([[12343.51498552],
       [12374.59251617],
       [12643.69018465],
       [12389.73898709],
       [12597.51411958],
       [12780.3576933 ],
       [13021.10726324],
       [13562.97977957],
       [14172.86326381],
       [13932.80723512],
       [14013.89073032],
       [14722.00203168],
       [14146.65932052],
       [14892.23595473],
       [15014.89580769],
       [14519.8662196 ],
       [15132.48778737],
       [15145.38988797],
       [15555.45573161],
       [15350.26955183],
       [14498.05597409],
       [14425.72497455]])

In [11]:
lm.score(x, y)

0.8063569576036422

In [12]:
lm.coef_

array([[   0.        ,    0.4837773 ,  130.3150502 ,   -6.46780263,
        -276.37273409]])

In [13]:
lm.intercept_

array([10399.93334598])

In [29]:
import numpy as np

A = np.mean(np.abs(model.resid / y['y'])) * 100
A

2.5974298012728068